### ISSUE TITLE
Support Markdown and JSON files?

### ISSUE THREAD

**Issue by PeterDaveHello** [Raychanan/ChatGPT-for-Translation#10]
Thanks for this tool!

Currently JSON looks like supported, input a json file will got this:

```
Traceback (most recent call last):
  File "/x/./ChatGPT-for-Translation/ChatGPT-translate.py", line 359, in <module>
    main()
  File "/x/./ChatGPT-for-Translation/ChatGPT-translate.py", line 355, in main
    process_file(input_path, options)
  File "/x/./ChatGPT-for-Translation/ChatGPT-translate.py", line 319, in process_file
    if not check_file_path(file_path, options):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/x/./ChatGPT-for-Translation/ChatGPT-translate.py", line 288, in check_file_path
    raise Exception("Please use a txt file or URL")
Exception: Please use a txt file or URL
```

Though Markdown won't have the same error, but the Markdown format will be missing after the translation.

Is that something you'd like to support? Many thanks again!

**Comment by Raychanan** [comment]
The first feature request appears to be a relatively simple task. I will add that to the list. I am not certain if the GPT API will keep the raw markdown format, which will determine whether this feature can be supported. I will have a look at this over the weekend.

**Comment by PeterDaveHello** [comment]
Thanks @Raychanan, maybe it's up to the prompt we use to decide if the format can be preserved? Like using a code block and ask GPT to keep it.

**Comment by Raychanan** [comment]
Unfortunately, I won't be able to work on your requests this week as I was attempting to integrate PDF parsing. Apologies.

**Comment by PeterDaveHello** [comment]
Don't worry 😄 Thanks for your update 😃

**Comment by makerjackie** [comment]
right now, translate markdown have syntax error, for example, `[title](link)` translate to `标题（链接）` which obviously not a valid markdown syntax

**Comment by Raychanan** [comment]
Changes were made for the GPT prompt. Try again and let me know if the issue persists.

**Comment by PeterDaveHello** [comment]
Just test it and it looks like the format will brake, and the keys will also be translated, which isn't support to be 😅

**Comment by Raychanan** [comment]
Here's the prompt for the model. If it still doesn't maintain the format, I apologize as I'm currently out of ideas for improvements. Please let me know if you can suggest a better prompt for this specific situation.

```
Translate the following text into {target_language}. Retain the original format. Return only the translation and nothing else:\n{text}
```
