### ISSUE TITLE
成功运行，但字数受限

### ISSUE THREAD

**Issue by Xh-xie** [Raychanan/ChatGPT-for-Translation#12]
首先非常感谢你的工作，但在google colab翻译一个长文本时提示：
“This model's maximum context length is 4097 tokens. However, your messages resulted in 136752 tokens. Please reduce the length of the messages.Rate limit hit. Sleeping for 8 seconds.”
请问是openai api那边的限制还是本模型的限制，非常感谢。

**Comment by Raychanan** [comment]
Hi, this is due to the limitation of GPT models. Try splitting your long text into shorter ones might help.

你好，是GPT限制。试试手动切分为短段落。

**Comment by Xh-xie** [comment]
感谢回答。但是pdf很难切分段落，市面上转换软件大多都会排版错误。您可以添加一个解析PDF为txt下载但不翻译的功能吗？或者我了解到您对scipdf进行了一些调整以允许用户无需在本地初始化服务器即可解析 PDF，您能对这部分打包一下吗？我对这部分很感兴趣，我尝试部署scipdf的项目，但是无法成功。

**Comment by Raychanan** [comment]
所有被解析的PDF都已经被保存为 `pdf_filename_extracted.txt` 的形式了，在与源PDF同一个文件夹下。你看看呢。

"可以添加一个解析PDF为txt下载但不翻译的功能吗？" -- 先试试瞎填一个OpenAI密钥。

"能对这部分打包一下吗？我对这部分很感兴趣，我尝试部署scipdf的项目，但是无法成功。" 过几天我会单独把这个功能和另外写的一些代码结合，看看能不能单独发一个类似 "import paper_helper" 的小工具
