### ISSUE TITLE
代码更新后txt翻译失败

### ISSUE THREAD

**Issue by laoliloal** [Raychanan/ChatGPT-for-Translation#13]
如题。今天在Colab上跑代码，把所有txt放到一个文件夹后让它翻译，运行失败，显示“拓展名需要是txt” 【注】。
将代码回滚到上一版本，运行正常。

辛苦作者检查一下更新的代码，感谢！

【注：大意如此，我没有复制报错信息就把代码修改了，现在正在跑翻译。
若需要具体报错信息，等跑完后我可以重新改回去看一下。】

**Comment by Raychanan** [comment]
已回到上个版本，如果还不行请再告诉我

**Comment by laoliloal** [comment]
目前使用正常，谢谢！
