### ISSUE TITLE
希望能支持自定义openaiAPI代理地址

### ISSUE THREAD

**Issue by darknesscho** [Raychanan/ChatGPT-for-Translation#16]
如标题，如果能像自定义API-KEY一样自定义API代理地址就更方便了，感谢！
As the title suggests, it would be more convenient if we could customize the API proxy address just like customizing the API-KEY. Thank you!

**Comment by Raychanan** [comment]
不太理解这个需求。Google Colab上运行，应该不需要设置代理？
