### ISSUE TITLE
是不是现在chatgpt API 有限制了，我这边翻译不了了，一定要GPT plus嘛？

### ISSUE THREAD

**Issue by Simoncatty** [Raychanan/ChatGPT-for-Translation#17]
Rate limit reached for default-gpt-3.5-turbo in organization org-hQElk3GZ2kGv8Z5GB3k3Qm on requests per min. Limit: 3 / min. Please try again in 20s. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
Rate limit hit. Sleeping for 16 seconds.

**Comment by Raychanan** [comment]
`Limit: 3 / min.`

如果你说的 GPT plus 指的是在 OpenAI 中添加银行卡支付方式的话，是的。

如果没有办法，一个常用的备选方式是 Azure 云服务内的 OpenAI API. 当前项目已经支持使用 Azure 云服务内的 OpenAI API
