### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'. 

### ISSUE THREAD

**Issue by yTobin** [Raychanan/ChatGPT-for-Translation#18]
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory. 请问一下，我使用示例数据也是这种情况，这该怎么解决呢？

**Comment by Raychanan** [comment]
你好，`en_core_web_sm` 是 spacy 包内要求的模型。

打开终端，运行如下代码:
```
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
```

如果不想安装，Google Colab上可以正常运行代码。链接见这个项目的首页
