### ISSUE TITLE
File path input is not working

### ISSUE THREAD

**Issue by hyyz17200** [Raychanan/ChatGPT-for-Translation#2]
Thanks for creating this project! It's been really helpful so far.

I've been using the folder path as input and it's been working fine. However, when I switched to using a file path like "test.txt", it didn't work on my Windows 10 and Debian 11 machines. I didn't get any output and the file wasn't generated.

Additionally, I noticed that some processing sentences are appearing in the output file, which shouldn't be there. Could you please look into this issue as well?
 "把以下文本翻译成简体中文，忠实于原始文本。不要翻译人名和作者姓名。仅返回翻译内容，不要有其他内容："

Just wanted to bring this to your attention and see if you had any suggestions for fixing it. Thanks in advance!

**Comment by Raychanan** [comment]
Regarding the issue you raised with the file path input not working on Windows 10 and Debian 11, I have addressed this problem and made the necessary changes to the code. The issue should now be resolved.

I have also fine-tuned the model prompt to ensure that there are no processing sentences appearing in the output file. On my end, there are no more Chinese characters as you mentioned. However, I would appreciate it if you could give it a try on your end and let me know if the issue still persists.

**Comment by hyyz17200** [comment]
Yes, both the path input and processing sentence issues, are fixed right now. 

Thank you very much! 👍
