### ISSUE TITLE
似乎源代碼的ThreadPoolExecutor Function參數出了問題

### ISSUE THREAD

**Issue by YChanHuang** [Raychanan/ChatGPT-for-Translation#21]
This is error message
`AttributeError: 'Namespace' object has no attribute 'not_to_translate_people_names'`

**Comment by saintnever** [comment]
same here

**Comment by Raychanan** [comment]
Fixed. Please try again and let me know if the issue persists.

**Comment by YChanHuang** [comment]
Thanks, it's fixed
