### ISSUE TITLE
[Error] TF-TRT Warning: Could not find TensorRT

### ISSUE THREAD

**Issue by YChanHuang** [Raychanan/ChatGPT-for-Translation#22]
I am not so sure if this module `TensorRT` does anything, but it seems the whole module works fine without this

**Comment by Raychanan** [comment]
The warning messages you see are generated by the `scipdf` module, which is another project designed for parsing academic PDFs. These warnings can be safely ignored. Hope this helps.

**Comment by yTobin** [comment]
I translate pdf. and program presented Package punkt is already up-to-date! File extension  is not allowed. how do you resolve it ？

**Comment by Raychanan** [comment]
The example script on the project's homepage in Google Colab does not show this error. Make sure that your file has a `.pdf` extension. If the problem persists, provide us with your file.
