### ISSUE TITLE
PDF translation resulted in scrumbled lines in docx

### ISSUE THREAD

**Issue by VictoriaJune** [Raychanan/ChatGPT-for-Translation#27]
The result docx file when translating from pdf has messed up format and overlapping lines, making it hard to read.
[https://ibb.co/Pm944Hq](url)
![A3C6FA6F-C518-4916-ADE4-203E6FFC0FE5_4_5005_c](https://github.com/Raychanan/ChatGPT-for-Translation/assets/49620795/4c689ddf-cfe3-4a4d-befe-d74a314726d4)

**Comment by Raychanan** [comment]
You should be able to locate a "_translated.txt" text file in the same folder. Just copy and paste its content into a new Word document. This should do the trick for you.
