### ISSUE TITLE
An error occurred during translation: RetryError[<Future at 0x7f5ea65cb280 state=finished raised RateLimitError>]

### ISSUE THREAD

**Issue by wangyj1** [Raychanan/ChatGPT-for-Translation#28]
一串类似于以下的字符：
An error occurred during translation: RetryError[<Future at 0x7f5ea65cb280 state=finished raised RateLimitError>]

只有文档的一小部分被翻译

**Comment by Raychanan** [comment]
测试中还没有碰到过这种情况。如果使用的是 openai 官方API，你需要确保你绑定了支付方式。如果无法绑定支付，只能使用 Azure 上的 GPT API。
