### ISSUE TITLE
Error while  run "pip install -r requirements.txt --quiet" on colab

### ISSUE THREAD

**Issue by myriad2** [Raychanan/ChatGPT-for-Translation#29]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.27.1, but you have requests 2.31.0 which is incompatible.

**Comment by Raychanan** [comment]
This occurs because the requirements.txt file specifies the "requests" package without explicitly stating its version. As a result, pip searches for the most recent package versions.

For your information, **you can simply disregard the warning**, and the program should still function properly.
