### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by LeePheon** [Raychanan/ChatGPT-for-Translation#32]
I would like use openai's official proxy: https://api.openai-proxy.com/
or other proxies.
Could you show how to set openai_base_url?

**Comment by Raychanan** [comment]
Hi there! I may add support for this functionality later, but for now, you can easily overcome those technical difficulties by using the Google Colab example notebook seen on this project's homepage.

**Comment by Raychanan** [comment]
I won't be implementing this functionality due to the risks associated with using proxies and the possibility of being banned by OpenAI. Plus, Google Colab has made it much easier to work without proxies.
