### ISSUE TITLE
Formulas and pictures

### ISSUE THREAD

**Issue by yangshuai-edu** [Raychanan/ChatGPT-for-Translation#34]
It would be more perfect if the formulas and pictures of the original document could be retained in the translated article.

**Comment by Raychanan** [comment]
The project is centered around Grobid, a machine learning software designed to extract information from scholarly documents. While it performs well in most cases, there are some limitations when it comes to extracting formulas. In fact, in many cases, it would be more effective to remove the formulas altogether.

However, you do have the option of providing your own text and inputting it into the current code script.
