### ISSUE TITLE
進度條跑完後生成的txt以及docx裡面都沒東西

### ISSUE THREAD

**Issue by Jay920314** [Raychanan/ChatGPT-for-Translation#35]
不管是用自己電腦跑還是goolge那東西跑，跑完之後生成的文件裡面都沒內容，完全空白的。
python啥的這部分我是真小白，搞半天才跑成但一直沒東西真的很沮喪，有解嗎？

**Comment by Raychanan** [comment]
如果文件是PDF，你需要确保文件是完整的并且你可以手工从中复制“可读”的文字。换句话说，如果你都无法手工提取可读信息，电脑更不可以。

如果是其它文件格式，提供你的文档或者其中一部分会有助于我弄清楚是什么问题。

**Comment by Cris-Young** [comment]
我遇到了相同的问题，我翻译的文件是内置的input.txt文件，并且文档具有正常的读写权限，但是在程序提示翻译成功后生成的文件中，我没有找到翻译后的文档，input_translated.txt打开后是空白

**Comment by Raychanan** [comment]
OpenAI API 里面要绑定支付方式，否则会有极其严苛的API速率限制

**Comment by Yun-Tianming** [comment]
> OpenAI API 里面要绑定支付方式，否则会有极其严苛的API速率限制

我已经绑定了支付方式还是出现了这样的情况，不过除了一开始的认证，我的信用卡还未被扣除费用过，不知道是不是与这个有关
