### ISSUE TITLE
为啥报错了呀

### ISSUE THREAD

**Issue by Cris-Young** [Raychanan/ChatGPT-for-Translation#36]
Traceback (most recent call last):
  File "ChatGPT-translate.py", line 15, in <module>
    from tenacity import (
ModuleNotFoundError: No module named 'tenacity'

**Comment by Raychanan** [comment]
因为No module named 'tenacity'。

你可以直接在Google Colab上使用这个工具(推荐)。见[这里](https://colab.research.google.com/drive/1_715zHeS3VaZaB9ISyo29Zp-KOTsyP8D#scrollTo=hU-8gsBXAyf0)

**Comment by Cris-Young** [comment]
请问有这个包的源路径吗，我直接pip安装这个包好像找不到

**Comment by Cris-Young** [comment]
可以了，用阿里云的镜像安装之后就可以了，感谢
