### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by Cris-Young** [Raychanan/ChatGPT-for-Translation#37]
An error occurred during translation: RetryError[<Future at 0x1a88dfc88b0 state=finished raised AttributeError>]
请问是什么原因呢

**Comment by Cris-Young** [comment]
key是可以用的，文件也有正常的读写权限

**Comment by Raychanan** [comment]
OpenAI API 里面要绑定支付方式，否则会有极其严苛的API速率限制
