### ISSUE TITLE
跑完后生成的文件空白，跑的过程中控制台输出An error occurred during translation: RetryError[<Future at 0x25dc6ab8450 state=finished raised InvalidRequestError>]

### ISSUE THREAD

**Issue by crushh** [Raychanan/ChatGPT-for-Translation#38]
<img width="720" alt="image" src="https://github.com/Raychanan/ChatGPT-for-Translation/assets/30379665/1f6fcddd-0759-4fea-b425-46d82dfb762d">

**Comment by crushh** [comment]
使用的文档就是仓库里自带的txt文档

**Comment by Raychanan** [comment]
OpenAI API 里面要绑定支付方式，否则会有极其严苛的API速率限制
