### ISSUE TITLE
关于翻译pdf论文相关问题

### ISSUE THREAD

**Issue by Daydaylight** [Raychanan/ChatGPT-for-Translation#40]
感谢您分享的优秀项目，我有一个问题想请教一下您。
在翻译pdf论文时，这个是如何处理其中的公式和排版的？这个翻译含数学公式的学术论文的效果好不好？

**Comment by Raychanan** [comment]
你好！
这个翻译含数学公式的学术论文的效果好不好？——非常不好。

基于测试，对公式的识别效果很糟糕因此在当前项目中已经默认移除了所有公式。

你可以通过 mathpix 将文本转换为 txt 文档，然后喂给当前项目一个 txt 文档，而非 PDF 文件

**Comment by Daydaylight** [comment]
> 

懂了
非常感谢您的回复和建议。
