### ISSUE TITLE
翻译的结果是空白

### ISSUE THREAD

**Issue by Yun-Tianming** [Raychanan/ChatGPT-for-Translation#41]
Bilingual text只有英文，Translated text是空白。。。

**Comment by Raychanan** [comment]
Google Colab上使用这个工具(推荐)。见[这里](https://colab.research.google.com/drive/1_715zHeS3VaZaB9ISyo29Zp-KOTsyP8D#scrollTo=hU-8gsBXAyf0)

使用这个链接得到的结果均为正常。如果还是有问题，请告知
