### ISSUE TITLE
Translate epub

### ISSUE THREAD

**Issue by sonzin** [Raychanan/ChatGPT-for-Translation#45]
I think your app is very good and has fast processing speed. However, I wanted to ask if you have any plans to develop the feature of translating epub files. Currently, there are many books and documents in epub format, so it would be great if you could add the ability to translate this format. Thank you very much!

**Comment by Raychanan** [comment]
Check out this GitHub repository, it should address your request:

https://github.com/jesselau76/ebook-GPT-translator
