### ISSUE TITLE
遇到了一个报错

### ISSUE THREAD

**Issue by tiyi0817** [Raychanan/ChatGPT-for-Translation#46]
<img width="646" alt="屏幕截图 2023-09-22 195519" src="https://github.com/Raychanan/ChatGPT-for-Translation/assets/132325703/d0134e66-32ac-45ca-936e-13d9a22be181">

**Comment by Raychanan** [comment]
https://colab.research.google.com/drive/1_715zHeS3VaZaB9ISyo29Zp-KOTsyP8D 用这个来处理你的文件。

**Comment by tiyi0817** [comment]
多谢
