### ISSUE TITLE
Translation added extra text for code section

### ISSUE THREAD

**Issue by chenqiny** [Raychanan/ChatGPT-for-Translation#49]
This tool add a section to result.

like 
请打开窗帘。  
狗正在追逐猫。  
她喜欢吃巧克力。  
他们已经到达目的地。  
我们明天见。  
将以下文本翻译成简体中文。保留原始格式。只返回翻译部分，不返回其他内容：  

**To be translated:**

## [AutoGPT Forge Part 1: A Comprehensive Guide to Your First Steps](https://aiedge.medium.com/autogpt-forge-a-comprehensive-guide-to-your-first-steps-a1dfdf46e3b4)

![Header](../../../docs/content/imgs/quickstart/000_header_img.png)

**Written by Craig Swift &** [**Ryan Brandt**](https://github.com/paperMoose)

Welcome to the getting started Tutorial! This tutorial is designed to walk you through the process of setting up and running your own AutoGPT agent in the Forge environment. Whether you are a seasoned AI developer or just starting out, this guide will equip you with the necessary steps to jumpstart your journey in the world of AI development with AutoGPT.

## Section 1: Understanding the Forge

The Forge serves as a comprehensive template for building your own AutoGPT agent. It not only provides the setting for setting up, creating, and running your agent, but also includes the benchmarking system and the frontend for testing it. We'll touch more on those later! For now just think of the forge as a way to easily generate your boilerplate in a standardized way.

## Section 2: Setting up the Forge Environment

To begin, you need to fork the [repository](https://github.com/Significant-Gravitas/AutoGPT) by navigating to the main page of the repository and clicking **Fork** in the top-right corner.

![The Github repository](../../../docs/content/imgs/quickstart/001_repo.png)

Follow the on-screen instructions to complete the process.

![Create Fork Page](../../../docs/content/imgs/quickstart/002_fork.png)

### Cloning the Repository

Next, clone your newly forked repository to your local system. Ensure you have Git installed to proceed with this step. You can download Git from [here](https://git-scm.com/downloads). Then clone the repo using the following command and the url for your repo. You can find the correct url by clicking on the green Code button on your repos main page.  
 

![img_1.png](../../../docs/content/imgs/quickstart/003A_clone.png)

```bash
# replace the url with the one for your forked repo
git clone https://github.com/<YOUR REPO PATH HERE>
```

![Clone the Repository](../../../docs/content/imgs/quickstart/003_clone.png)

**Result**

## [AutoGPT Forge 第1部分：全面指南帮你迈出第一步](https://aiedge.medium.com/autogpt-forge-a-comprehensive-guide-to-your-first-steps-a1dfdf46e3b4)

![Header](../../../docs/content/imgs/quickstart/000_header_img.png)

  
由Craig Swift & [Ryan Brandt](https://github.com/paperMoose)撰写  
欢迎来到入门教程！本教程旨在引导您在Forge环境中设置和运行自己的AutoGPT代理程序。无论您是一位经验丰富的AI开发者还是初学者，本指南都将为您提供必要的步骤，帮助您开始自己在AutoGPT的人工智能开发世界中的旅程。  
第一部分：了解锻炉  
The Forge（锻造台）用作创建自己的AutoGPT代理的综合模板。它不仅提供了设置、创建和运行代理的设置，还包括基准测试系统和用于测试的前端。稍后我们会更详细介绍这些内容！现在只需将锻造台视为以标准化方式轻松生成模板的方法。

## 第二节：设置铸造环境

首先，您需要通过导航到存储库的主页并在右上角单击“Fork”来进行复制[存储库](https://github.com/Significant-Gravitas/AutoGPT)。  
 

![Github 仓库](../../../docs/content/imgs/quickstart/001_repo.png)

  
按照屏幕上的指示完成流程。  
 

![创建派生页面](../../../docs/content/imgs/quickstart/002_fork.png)

### 克隆存储库

接下来，将您新分叉的存储库克隆到您的本地系统。确保您已经安装了Git才能进行此步骤。您可以从[这里](https://git-scm.com/downloads)下载Git。然后使用以下命令和存储库的URL克隆存储库。您可以通过单击存储库主页上的绿色代码按钮找到正确的URL。  
 

![img_1.png](../../../docs/content/imgs/quickstart/003A_clone.png)

  
请打开窗帘。  
狗正在追逐猫。  
她喜欢吃巧克力。  
他们已经到达目的地。  
我们明天见。  
将以下文本翻译成简体中文。保留原始格式。只返回翻译部分，不返回其他内容：  
＃用指向您分支仓库的URL替换URL

```python
def foo(bar):
    """
    This function takes in a parameter 'bar' and returns a string.
    """
    return 'Hello ' + bar
url = 'http://www.example.com'
```

```html
<h1>This is a heading</h1>
<p>This is a paragraph.</p>
<a href="{{ url }}">Click here</a>
```

```shell
$ git clone https://www.example.com/repo.git
```

```javascript
var x = 5;
var y = 10;
var z = x + y;
console.log(z);
```

```ruby
puts "Hello, world!"
```

```php
<?php
echo "Hello, world!";
?>
```

```markdown
# Title
This is a paragraph.
```

```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
```

```bash
#!/bin/bash
echo "Hello, world!"
```

```c
#include <stdio.h>
int main() {
   printf("Hello, world!");
   return 0;
}
```

```cpp
#include <iostream>
int main() {
    std::cout << "Hello, world!";
    return 0;
}
```

```python
def say_hello():
    print("Hello, world!")
say_hello()
```

```css
body {
    background-color: #f3f3f3;
    color: #333;
    font-family: Arial, sans-serif;
}
h1 {
    font-size: 24px;
    font-weight: bold;
}
a {
    color: blue;
    text-decoration: none;
}
```

```xml
<root>
    <element>This is an element</element>
    <anotherelement>This is another element</anotherelement>
</root>
```

```sql
SELECT * FROM table_name;
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>Hello, world!</title>
</head>
<body>
    <h1>Hello, world!</h1>
</body>
</html>
```

```python
# This is a comment
name = 'Alice'  # This is another comment
print('Hello, ' + name)
```

git克隆 https://github.com/\<你的存储库路径在这里>  
请注意：以下活动已经取消。  
日期：2020年5月15日  
时间：下午2点至4点  
地点：大会议室  
希望大家能及时收到通知，并做好调整。  
谢谢！  
克隆存储库

**Comment by Raychanan** [comment]
This pertains to the behavior of ChatGPT. I'm afraid I don't have any insight or ability to rectify the behavior of OpenAI's model.
