### ISSUE TITLE
Please reduce the length of the messages.

### ISSUE THREAD

**Issue by f0rmatme** [Raychanan/ChatGPT-for-Translation#6]
This model's maximum context length is 4097 tokens. However, your messages resulted in 5737 tokens. Please reduce the length of the messages.

Can you do something like batches for larger files?

**Comment by Raychanan** [comment]
Will do...

**Comment by Raychanan** [comment]
Changes were made to address this issue by utilizing nltk's sentence tokenizer. In cases where a paragraph exceeds 4000 words, I divide the text into two and merge their translations before presenting it back to the user. Hope this helps.
