### ISSUE TITLE
We need a version that supports browser login not via API

### ISSUE THREAD

**Issue by FurkanGozukara** [Raychanan/ChatGPT-for-Translation#7]
I got chatGPT plus

it can translate entire subtitle but you have to split it into like 1 minute frames and type again and again

which takes huge time

can you modify it so that we can use chat GPT plus subscription not API?

**Comment by Raychanan** [comment]
The cost of translating an entire book is a mere 2 US dollars! However, this project is small and intended for my personal use in some cases. While your suggestion is fantastic, it is beyond the scope of what I had originally envisioned. Sorry.

**Comment by FurkanGozukara** [comment]
> The cost of translating an entire book is a mere 2 US dollars! However, this project is small and intended for my personal use in some cases. While your suggestion is fantastic, it is beyond the scope of what I had originally envisioned. Sorry.

mere 2 dollars is a good money for Turkey 🗡️ 
consider that I can translate hundreds of 60 minutes subtitles to 100 different languages with chatGPT plus subscription for just 20$  :D

**Comment by FurkanGozukara** [comment]
@Raychanan this doesnt support vtt or srt subtitle format right?
